# Generated by Django 5.2.4 on 2025-08-12 00:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accepted_terms_at", models.DateTimeField(auto_now_add=True)),
                ("privacy_version", models.CharField(max_length=20)),
                ("marketing_opt_in", models.BooleanField(default=False)),
                (
                    "client_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, unpack_ipv4=True
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
