# Generated by Django 5.2.4 on 2025-08-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0003_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
