# Generated by Django 5.2.4 on 2025-08-11 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0004_post_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("basic", "워홀 기본 정보"),
                    ("jobs_housing", "일자리 & 숙소"),
                    ("guide", "가이드"),
                    ("travel", "워홀 후기 & 여행"),
                    ("qna", "q&a"),
                ],
                db_index=True,
                default="basic",
                max_length=20,
            ),
        ),
    ]
