# Generated by Django 5.2.4 on 2025-08-14 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0005_post_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=50),
        ),
    ]
