# Generated by Django 5.2.4 on 2025-08-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0006_alter_post_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_pinned",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
