# Generated by Django 5.2.4 on 2025-08-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0007_post_is_pinned"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="is_pinned",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="공지(상단 고정)"
            ),
        ),
    ]
