# Generated by Django 5.2.4 on 2025-08-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0008_alter_post_is_pinned"),
    ]

    operations = [
        migrations.CreateModel(
            name="UniqueVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("fp", models.CharField(max_length=64)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("ua", models.TextField(blank=True)),
                ("path", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["date", "fp"], name="board_uniqu_date_e25ed7_idx"
                    )
                ],
                "unique_together": {("date", "fp")},
            },
        ),
    ]
