# Generated by Django 5.2.4 on 2025-09-05 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("board", "0009_uniquevisit"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UniqueVisit",
        ),
    ]
